In [3]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.
#from IPython.display import display
import numpy as np
import pandas as pd


# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [19]:
#Create an array of 10 zeros
my_array = np.zeros(10)

#set the fifth element to 1
my_array[4] = 1

#display(my_array)
print(my_array)

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Score": [95, 80, 90]
})

# Display the DataFrame
print(df)
#print(df)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
      Name  Age  Score
0    Alice   25     95
1      Bob   30     80
2  Charlie   35     90


### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [20]:
# create a 4x4 matris

matrix = np.arange(16).reshape(4, 4)

#display result
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [6]:
# # solution
arr1 = np.array([[41,30,10],[6,35, 23], [23, 9, 10]])
arr2 = np.array([[4, 29, 2], [5, 13, 3], [24, 16, 7]])
# addition: arr1 + arr2
addition_result = arr1 + arr2
#addition_result

# subtraction: arr1 - arr2 
subtraction_result = arr1 - arr2

# division: arr1 / arr2
division_result = arr1 / arr2

# multiplication: arr1 * arr2
multiplication_result = arr1 * arr2

#display the result
print("Addition: ",addition_result)
print("Subtraction: ",subtraction_result)
print("Division: ",division_result)
print("Multiplication: ",multiplication_result)

Addition:  [[45 59 12]
 [11 48 26]
 [47 25 17]]
Subtraction:  [[37  1  8]
 [ 1 22 20]
 [-1 -7  3]]
Division:  [[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]]
Multiplication:  [[164 870  20]
 [ 30 455  69]
 [552 144  70]]


### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [ ]:
# Give array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

#Extra elements from index 2 to 6
extract_elements = arr[2:7]

print(extract_elements)


array([30, 40, 50, 60, 70])

### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [7]:
# solution
#convert the array below to a 3 x 3 numpy array.
numpy_array = [[15, 18, 20], [15, 30, 8], [25, 30, 60]]

#dispay array


# Convert the array to 3x3 numpy array
numpy1_array = np.array(numpy_array)

#Calculate the mean, sum and maximum value
mean_value = numpy1_array.mean()
#NB: round the mean to two decimal places
mean_value_round = round(mean_value, 2)
sum_value = numpy1_array.sum()
max_value = numpy1_array.max()

print("Mean Value:", mean_value_round)
print("Sum Value: ", sum_value)
print("Maximum Value: ", max_value)



Mean Value: 24.56
Sum Value:  221
Maximum Value:  60


# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [8]:
# Create a pandas series from the list [10, 20, 30, 40, 50] with index labels 'a','b','c'
data = [10, 20, 30, 40, 50]
index_labels = ['a', 'b', 'c', 'd', 'e']

series = pd.Series(data, index=index_labels)

print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [9]:
# Read a CSV file named "data.csv" into a pandas dataFrame. The CSV file has the following columns: "Name", "Age","Salary"
# Read the CSV file into a DataFrame
df = pd.read_csv("data/data.csv")
print(df)
#print(df.columns)

       Name  Age  Score
0     Alice   29  73193
1       Bob   53  85398
2   Charlie   36  47162
3     David   22  65853
4       Eve   24  36168
5     Frank   58  69657
6     Grace   41  85202
7    Hannah   38  62421
8     Isaac   50  74641
9      Jack   47  38963
10    Karen   34  32136
11      Leo   49  41874
12     Mona   56  34070
13     Nina   49  91734
14    Oscar   30  89539
15     Paul   23  78720
16    Quinn   31  54424
17   Rachel   54  59900
18    Steve   36  32163
19     Tina   56  52054


### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [10]:
# From the DataFrame created in Exercise 2, select only the first three rows
# Select the first three rows using slicing
first_three_rows = df[:3]

#Alternatively, you can use .iloc[]
first_three_rows = df.iloc[0:3]

print(first_three_rows)

      Name  Age  Score
0    Alice   29  73193
1      Bob   53  85398
2  Charlie   36  47162


### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [11]:
# # Add a new column named "Tax" 
df["Tax"] = df["Score"] * 0.10

print(df)

       Name  Age  Score     Tax
0     Alice   29  73193  7319.3
1       Bob   53  85398  8539.8
2   Charlie   36  47162  4716.2
3     David   22  65853  6585.3
4       Eve   24  36168  3616.8
5     Frank   58  69657  6965.7
6     Grace   41  85202  8520.2
7    Hannah   38  62421  6242.1
8     Isaac   50  74641  7464.1
9      Jack   47  38963  3896.3
10    Karen   34  32136  3213.6
11      Leo   49  41874  4187.4
12     Mona   56  34070  3407.0
13     Nina   49  91734  9173.4
14    Oscar   30  89539  8953.9
15     Paul   23  78720  7872.0
16    Quinn   31  54424  5442.4
17   Rachel   54  59900  5990.0
18    Steve   36  32163  3216.3
19     Tina   56  52054  5205.4


#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [12]:
# Filter rows where the "Age" column is greater than 36
filtered_age = df[df["Age"] > 36]

print(filtered_age)

      Name  Age  Score     Tax
1      Bob   53  85398  8539.8
5    Frank   58  69657  6965.7
6    Grace   41  85202  8520.2
7   Hannah   38  62421  6242.1
8    Isaac   50  74641  7464.1
9     Jack   47  38963  3896.3
11     Leo   49  41874  4187.4
12    Mona   56  34070  3407.0
13    Nina   49  91734  9173.4
17  Rachel   54  59900  5990.0
19    Tina   56  52054  5205.4


# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [13]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [14]:
# Group by "Region" and compute total and mean sales
total_sale_per_region = sales_data.groupby("Region")["Sales"].sum()
mean_sales_per_region = sales_data.groupby("Region")["Sales"].mean()

#Display the results
print("Total Sales per Region:")
print(total_sale_per_region)

print("Mean Sales per Region")
print(mean_sales_per_region)


Total Sales per Region:
Region
North    2200
South    2800
West     3500
Name: Sales, dtype: int64
Mean Sales per Region
Region
North    1100.0
South    1400.0
West     1750.0
Name: Sales, dtype: float64


### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [15]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), orders.head(2))

   CustomerID CustomerName
0           1        Alice
1           2          Bob    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [ ]:
# Merge the DataFrames based on "CustomerID"

merged_df = pd.merge(customers, orders, on="CustomerID")

print(merged_df)


CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150

### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [16]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2), departments.head(2))

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2    DeptID DeptName
0       1       HR
1       2  Finance


In [ ]:
# Perform a left join between employees and departments on "DeptID"

left_join_df = pd.merge(employees, departments, on="DeptID", how="left")

print(left_join_df)


EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN

### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [17]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [18]:
# Create a pivot table showing total sales for each Region and Product
pivot_table = pd.pivot_table(
    sales_pivot_data,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum"
)

print(pivot_table)


Product    A    B
Region           
North    200  300
South    150  400
West     250  500
